---
rvm:
  url: https://get.rvm.io
  temp_installer_path: /tmp/rvm-installer.sh
  required_packages:
    - curl
    - gnupg2

rvm_install_type: system
rvm_auto_update_rvm: true
rvm_default_ruby_version: ruby-2.2.2
rvm_gpg_keys: 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
item: hkp://pool.sks-keyservers.net